# Initializing a tensor
In this section we will practice the different ways of initializing a tensor object:

1. Import PyTorch and initialize a tensor by call

In [1]:
import torch
x = torch.tensor([[1, 2]])
y = torch.tensor([[1],[2]])
print(x)
print(y)

tensor([[1, 2]])
tensor([[1],
        [2]])


2. Next, access the tensor object's shape and data type

In [2]:
print(x.shape)
print(y.shape)
print(x.dtype)

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


The data type of all elements within a tensor is the same. That means if a tensor contains data of different data types (such as Boolean, an integer, and a float), the entire tensor is coerced to the most generic data type. 
*in this case* **floating-point**.

In [3]:
x = torch.tensor([False, 1, 2.0])
print(x)

tensor([0., 1., 2.])


3. Generate a tensor object that has three rows and four columns filled with zeros:

In [5]:
t = torch.zeros((3, 4))
print(t)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


4. Generate a tensor object that has three rows and four columns filled with ones:

In [4]:
t = torch.ones((3, 4))
print(t)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


5. Generate three rows and four columns of values between 0 and 10 (including the low value but not including the high value):

In [6]:
t = torch.randint(low=0, high=10, size=(3,4))
print(t)

tensor([[0, 7, 1, 7],
        [0, 0, 8, 5],
        [0, 0, 4, 6]])


6. Generate random numbers between 0 and 1 with three rows and four columns 

In [7]:
t = torch.rand(3, 4)
print(t)

tensor([[0.6409, 0.6411, 0.3576, 0.4624],
        [0.4630, 0.9037, 0.0264, 0.7680],
        [0.7666, 0.9510, 0.1309, 0.1673]])


7. Generate a numbers that follow a random distribution with three rows and four columns

In [8]:
t = torch.randn(3, 4)
print(t)

tensor([[ 0.5177,  2.0593, -2.1496,  0.1421],
        [ 1.0337,  0.4878,  0.3265, -0.2629],
        [ 0.4753, -2.0495, -0.4025,  0.1121]])


8. Finally, we can directly convert a NumPy array into a Torch tensor using `torch.tensor(<numpy-array>)`

In [10]:
import numpy as np
x = np.array([[10,20,30], [2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
